version: '3.8'

services:
  backuping:
    image: ${BACKUPING_IMAGE}
    restart: unless-stopped
    environment:
      BACKUPING_DB_HOST: mysql-server
      BACKUPING_DB_USERNAME: ${WEBSHOT_DB_USERNAME}
      BACKUPING_DB_PASSWORD: ${WEBSHOT_DB_PASSWORD}
      BACKUPING_FTP_HOST: ${WEBSHOT_BACKUPING_FTP_HOST}
      BACKUPING_FTP_USERNAME: ${WEBSHOT_BACKUPING_FTP_USERNAME}
      BACKUPING_FTP_PASSWORD: ${WEBSHOT_BACKUPING_FTP_PASSWORD}
      BACKUPING_FTP_PATH: ${WEBSHOT_BACKUPING_FTP_PATH}
      BACKUPING_FTP_LIFETIME_IN_DAY: ${WEBSHOT_BACKUPING_FTP_LIFETIME_IN_DAY}
      BACKUPING_REPORT_ENABLED: ${WEBSHOT_BACKUPING_REPORT_ENABLED}
      BACKUPING_REPORT_SUBJECT: ${WEBSHOT_BACKUPING_REPORT_SUBJECT}
      BACKUPING_REPORT_SENDER_NAME: ${WEBSHOT_BACKUPING_REPORT_SENDER_NAME}
      BACKUPING_REPORT_SENDER_EMAIL: ${WEBSHOT_BACKUPING_REPORT_SENDER_EMAIL}
      BACKUPING_REPORT_RECEIVER_1_NAME: ${WEBSHOT_BACKUPING_REPORT_RECEIVER_1_NAME}
      BACKUPING_REPORT_RECEIVER_1_EMAIL: ${WEBSHOT_BACKUPING_REPORT_RECEIVER_1_EMAIL}
      BACKUPING_BACKUP_CRON_EXPRESSION: ${WEBSHOT_BACKUPING_BACKUP_CRON_EXPRESSION}
      BACKUPING_CLEANUP_CRON_EXPRESSION: ${WEBSHOT_BACKUPING_CLEANUP_CRON_EXPRESSION}
    depends_on:
      - web-shot
    volumes:
      - webshot-storage:/webshot/storage:ro
      - ./.docker/backuping/config.php:/app/packages/backuping/.docker/base/config.php

