version: '3.8'

services:
  mysql:
    environment:
      WEBSHOT_MYSQL_DATABASE: ${WEBSHOT_MYSQL_DATABASE}
      WEBSHOT_MYSQL_USER: ${WEBSHOT_MYSQL_USER}
      WEBSHOT_MYSQL_PASSWORD: ${WEBSHOT_MYSQL_PASSWORD}
    volumes:
      - ./.docker/mysql/docker-entrypoint-initdb.d/mysql-init.sh:/docker-entrypoint-initdb.d/00-webshot-mysql-init.sh:ro
      - ./database.sql:/docker-entrypoint-initdb.d/01-webshot-database.sql.seed:ro
      - ./.docker/mysql/docker-entrypoint-initdb.d/database.sql:/docker-entrypoint-initdb.d/02-webshot-patch.sql.seed:ro

  web-shot:
    image: ${WEBSHOT_IMAGE}
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      WEBSHOT_MYSQL_HOST: mysql
      WEBSHOT_MYSQL_USER: ${WEBSHOT_MYSQL_USER}
      WEBSHOT_MYSQL_PASSWORD: ${WEBSHOT_MYSQL_PASSWORD}
      WEBSHOT_MYSQL_DATABASE: ${WEBSHOT_MYSQL_DATABASE}
      WEBSHOT_HOSTNAME: ${WEBSHOT_HOSTNAME}
    security_opt:
      - seccomp:./chrome.json
    volumes:
      - webshot-storage:/home/webshot/dist/storage/
    depends_on:
      - mysql

volumes: 
  webshot-storage:
